tagungsuhr/cal/urls.py
from django.urls import path

from . import views

app_name = "cal"
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add")
]

tagungsuhr/tagungsuhr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('tagungsuhr_test.urls')),  # Get all URLS from test app
    path('cal/', include('cal.urls'))
]
 

tagungsuhr/tagungsuhr_test/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),  # Default app. Run index-function which is one of my views
    path('tagungsuhr_test/', views.tagungsuhr_test),
    path('extra/', views.extra)
]

tagungsuhr/cal/models.py
from django.db import models

# Create your models here.

tagungsuhr/tagungsuhr_test/models.py
from django.db import models

# Create your models here.

tagungsuhr/cal/views.py
from django.shortcuts import render
from django.http import HttpRequest
import datetime as dt
from django import forms
# Create your views here.

days = [dt.datetime.now(), dt.datetime.today() + dt.timedelta(days=1)]
json = []

class NewCalForm(forms.Form):
    date_from_form = forms.DateField(label="Neues Datum")
    text = forms.CharField()

def index(request):
    return render(request, "cal/index.html", {
        "days" : days
    })

def add(request):
    if request.method == "POST":  
        form = NewCalForm(request.POST)
        if form.is_valid():
            date = form.cleaned_data['date_from_form']  # All submited userdata. Name in [] comes from NewCalForm
            days.append(date)
    else:
        form = NewCalForm(request.GET)
    return render(request, "cal/add.html", {
        "form": NewCalForm()
    })

tagungsuhr/tagungsuhr_test/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
# Create your views here.
def index(request):  # Get the HTTP request from a user
    return render(request, "home/index.html")

def tagungsuhr_test(request):
    return render(request, "home/tagungsuhr_test.html")

def extra(request):  # Get the HTTP request from a user
    now = datetime.now()
    return render(request, "home/extra.html", {
        "newyear": now.month == 1 and now.day == 1
    })

tagungsuhr/cal/templates/cal/add.html
{% extends "cal/layout.html" %}

{% block body %}
    <h1>Datum eintragen</h1>
    <form action="{% url 'cal:add' %}" method="post">
        
        {{form}}
        <input type="submit">
    </form>
    <a href="{% url 'cal:index' %}">Zurück zur Übersicht</a>
{% endblock %}

tagungsuhr/cal/templates/cal/index.html
{% extends "cal/layout.html" %}

    {% block body %}
    <h1>Kalendereinträge</h1>
    <h3>Beispiel</h3>
    <ul>
        {% for day in days %}
            <li>{{day}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'cal:add' %}">Neues Datum eintragen</a>
    {% endblock %}

tagungsuhr/cal/templates/cal/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Kalenderansicht</title>
        <h3>Beispiel</h3>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

tagungsuhr/tagungsuhr_test/templates/home/extra.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Extra</title>
        <link href="{% static 'styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Ist es heute Weihnachten?</h1>
        {% if newyear %}
            <h1>Ja</h1>
        {% else %}
            <h1>Nein</h1>
        {% endif %}
    </body>
</html>

tagungsuhr/tagungsuhr_test/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Homepage</title>
    </head>
    <body>
        
        <h1>Homepage</h1>
        <h2>Beispiel</h2>
        <h3>Beispiel</h3>
        <h4>Beispiel</h4>
        <h5>Beispiel</h5>
    </body>
</html>

tagungsuhr/tagungsuhr_test/templates/home/tagungsuhr_test.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tagungsuhr Test UI</title>
    </head>
    <body> 
        <h3>Beispiel UI</h3>
    </body>
</html>